### ISSUE TITLE
Problem with detect_script?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaText/Languages.jl#14]
https://github.com/JuliaText/Languages.jl/blob/d0eef05242903c41ea8879a9c3f5a2330ea83675/src/whatlang.jl#L65-L67 seems wrong. Should the first line be mutating `sort!`, the middle be `script_counters[1][2]`, and the final be `script_counters[1][1]`? An error can be triggered with

```julia
julia> Languages.detect_script("")
ERROR: MethodError: no method matching isless(::Int64, ::Array{Any,1})
Closest candidates are:
  isless(::Real, ::AbstractFloat) at operators.jl:97
  isless(::Real, ::Real) at operators.jl:266
Stacktrace:
 [1] detect_script(::String) at /Users/andreasnoack/.julia/v0.6/Languages/src/whatlang.jl:66
```

**Comment by arc999** [comment]
@aviks I think this issue has been resolved.
![a1](https://user-images.githubusercontent.com/32388846/51838725-37e89280-232d-11e9-92c3-34bd5797bcf2.png)
